[workspace]
members = ["fvm", "fvm/example", "sdk", "sdk/example", "lib/*", "cgo/*/rust", "cgo/*/example/rust"]

[patch.crates-io]
multihash = { git = "https://github.com/multiformats/rust-multihash", branch = "next" }
cid = { git = "https://github.com/multiformats/rust-cid", branch = "next" }

[profile.actor]
inherits = "release"
panic = "abort"
overflow-checks = true
lto = true
opt-level = "z"
#strip = true