[package]
name = "fvm_example_actor"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
cid = "0.7.0"
fvm_sdk = { path = ".." }
