[package]
name = "ipld_amt-fuzz"
version = "0.0.0"
authors = ["ChainSafe Systems <info@chainsafe.io>", "Protocol Labs", "Filecoin Core Devs"]
publish = false
edition = "2018"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.3"
arbitrary = { version = "0.4", features = ["derive"] }
ahash = "0.6"

cid = { version = "0.8.2", default-features = false, features = ["serde-codec"] }

fvm_ipld_amt = {path = ".."}
fvm_shared = {path = "../../../shared"}

# Prevent this from interfering with workspaces
[workspace]
members = ["."]

[[bin]]
name = "simple"
path = "fuzz_targets/simple.rs"
test = false
doc = false

[[bin]]
name = "equivalence"
path = "fuzz_targets/equivalence.rs"
test = false
doc = false
