[package]
name = "ipld_hamt-fuzz"
version = "0.0.0"
authors = ["ChainSafe Systems <info@chainsafe.io>", "Protocol Labs", "Filecoin Core Devs"]
publish = false
edition = "2018"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.3"
arbitrary = { version = "0.4", features = ["derive"] }
ahash = "0.6"
fvm_shared = { path = "../../../shared" }

[dependencies.fvm_ipld_hamt]
path = ".."

# Prevent this from interfering with workspaces
[workspace]
members = ["."]

[[bin]]
name = "hamt_fuzz"
path = "fuzz_targets/hamt_fuzz.rs"
test = false
doc = false
