[package]
name = "cgobs-example"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["staticlib"]

[dependencies]
fvm_shared = { version = "0.1.0", path = "../../../shared", features = ["cgo"] }
cid = "0.7.0"