[package]
name = "fvm"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["lib"]

[dependencies]
anyhow = "1.0.47"
thiserror = "1.0.30"
blockstore = { path = "../lib/blockstore" }
num-traits = "0.2"
derive_builder = "0.9"
ahash = "0.6"
num-derive = "0.3.3"
cid = { version = "0.7", features = ["serde-codec"] }
multihash = { version = "0.15", features = ["identity", "default"] }
wasmtime = "0.31.0"
fvm_shared = { path = "../shared" }
ipld_hamt = { path = "../ipld/hamt"}
ipld_blockstore = { path = "../ipld/blockstore"}
ipld_amt = { path = "../ipld/amt"}
serde = { version = "1.0", features = ["derive"] }
serde_tuple = "0.5"
serde_repr = "0.1"
lazy_static = "1.4.0"
derive-getters = "0.2.0"
bls-signatures = { version = "0.9", default-features = false }
libsecp256k1 = "0.6"
filecoin-proofs-api = { version = "9", features = ["blst"], default_features = false, optional = true }

# FIXME: The FVM really shouldn't depend on this, but needs to for now.
actor = { package = "forest_actor", path = "../actor" }

[features]
default = ["blst", "proofs", "filecoin-proofs-api"]
proofs = []
blst = ["bls-signatures/blst"]
pairing = ["bls-signatures/pairing"]
derive_more = "0.99.17"
