[package]
name = "fvm"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["lib"]

[dependencies]
wasmer = "2.0.0"
# TODO: don't depend on this directly.
#cgobs = { git = "https://github.com/Stebalien/cgo-blockstore" }