name: Continuous integration

on:
  push:

jobs:
  rustfmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # v1.0.7
      with:
        profile: minimal
        override: true
        components: rustfmt
    - name: Run cargo clippy
      uses: actions-rs/cargo@844f36862e911db73fe0815f00a4a2602c279505 # v1.0.3
      with:
        command: fmt
        args: -- --check
  check-clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # v1.0.7
      with:
        profile: minimal
        target: wasm32-unknown-unknown
        override: true
        components: clippy
    # we don't check the lockfile in; this is needed for cache restoration/saving
    - uses: actions-rs/cargo@844f36862e911db73fe0815f00a4a2602c279505 # v1.0.3
      with:
        command: generate-lockfile
    - uses: Swatinem/rust-cache@842ef286fff290e445b90b4002cc9807c3669641 # v1.3.0
      with:
        # change this to invalidate cache for this job
        key: v0
    # otherwise the include_bytes! macro fails because this file hasn't been generated
    - run: touch examples/fvm/fvm_example_actor.wasm
      shell: bash
    - name: Run cargo clippy
      uses: actions-rs/cargo@844f36862e911db73fe0815f00a4a2602c279505 # v1.0.3
      with:
        command: clippy
        args: --all --all-targets
  build:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings
      RUSTC_WRAPPER: sccache
      SCCACHE_CACHE_SIZE: 2G
      SCCACHE_VERSION: v0.2.15
      SCCACHE_ASSET_NAME: sccache-v0.2.15-x86_64-unknown-linux-musl
      SCCACHE_DIR: ${{ github.workspace }}/.cache/sccache
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # v1.0.7
      with:
        target: wasm32-unknown-unknown
        override: true
    # we don't check the lockfile in; this is needed for cache restoration/saving
    - uses: actions-rs/cargo@844f36862e911db73fe0815f00a4a2602c279505 # v1.0.3
      with:
        command: generate-lockfile
    - uses: Swatinem/rust-cache@842ef286fff290e445b90b4002cc9807c3669641 # v1.3.0
      with:
        # change this to invalidate cache for this job
        key: v0
    - name: Install sccache
      run: |
        gh release download --repo 'mozilla/sccache' --dir '.' --pattern '${{ env.SCCACHE_ASSET_NAME }}.tar.gz' '${{ env.SCCACHE_VERSION }}'
        tar -zxf '${{ env.SCCACHE_ASSET_NAME }}.tar.gz'
        cp '${{ env.SCCACHE_ASSET_NAME }}/sccache' '/usr/local/bin/sccache'
        chmod +x '/usr/local/bin/sccache'
        mkdir -p '${{ env.SCCACHE_DIR }}'
        rm -r '${{ env.SCCACHE_ASSET_NAME }}'
        rm '${{ env.SCCACHE_ASSET_NAME }}.tar.gz'
        rust_version="$(rustc -vV)"
        rust_release="$(grep -oP 'release: \K.+' <<< "$rust_version")"
        rust_host="$(grep -oP 'host: \K.+' <<< "$rust_version")"
        rust_commit_hash="$(grep -oP 'commit-hash: \K.{0,12}' <<< "$rust_version")"
        restore_key="v0-sccache-v0-build-$rust_release-$rust_host-$rust_commit_hash"
        key="$restore_key-${{ hashFiles('**/Cargo.toml', '**/Cargo.lock', 'rust-toolchain', 'rust-toolchain.toml') }}"
        echo "SCCACHE_KEY=$key" >> $GITHUB_ENV
        echo "SCCACHE_RESTORE_KEY=$restore_key" >> $GITHUB_ENV
      shell: bash
    - name: Cache sccache
      uses: actions/cache@v2
      with:
        path: |
          ${{ env.SCCACHE_DIR }}
        key: ${{ env.SCCACHE_KEY }}
        restore-keys: |
          ${{ env.SCCACHE_RESTORE_KEY }}
    - name: Build on wasm32-unknown-unknown
      uses: actions-rs/cargo@844f36862e911db73fe0815f00a4a2602c279505 # v1.0.3
      with:
        command: build
        args: --features builtin_actors
  examples:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.17.3
    - uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # v1.0.7
      with:
        target: wasm32-unknown-unknown
        override: true
    # we don't check the lockfile in; this is needed for cache restoration/saving
    - uses: actions-rs/cargo@844f36862e911db73fe0815f00a4a2602c279505 # v1.0.3
      with:
        command: generate-lockfile
    - uses: protocol/cache-go-action@v1
    - uses: Swatinem/rust-cache@842ef286fff290e445b90b4002cc9807c3669641 # v1.3.0
      with:
        # change this to invalidate cache for this job
        key: v0
    - uses: actions-rs/cargo@844f36862e911db73fe0815f00a4a2602c279505 # v1.0.3
      with:
        command: install
        args: cbindgen
    - name: Build examples
      run: make examples
      shell: bash
